<!DOCTYPE html>
<html lang="en-US">
<head>

	<title>OpenWrt Forum Archive</title>

	<meta charset="UTF-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="assets/css/common.css">

</head>
<body>

<div class="container">

<header class="main-header">
	<h1 class="logo"><a href="index.html"><img src="assets/img/logo.png" width="376" height="88" alt="OpenWrt Forum Archive"></a></h1>
</header>

<aside>
	<p>This is a read-only archive of the old OpenWrt forum. The current OpenWrt forum resides at <a href="https://forum.openwrt.org/">https://forum.openwrt.org/</a>.</p>
	<p class="minor">In May 2018, the OpenWrt forum suffered a total data loss. This archive is an effort to restore and make available as much content as possible. Content may be missing or not representing the latest edited version.</p>
</aside>

<main>
	<header>
		<h1><span class="minor">Topic:</span> pyload no internet connection problem</h1>
	</header>
	<div class="notice minor">
		<p>
			The content of this topic has been archived
							on 2 May 2018.
										There are no obvious gaps in this topic, but there may still be some posts missing at the end.
					</p>
	</div>

	<div class="pagination"><div class="pagination-number">Page 1 of 1</div><nav><ul><li class="pagination-current"><span>1</span></li></ul></nav></div>
			
		
		
			<article class="post" id="p217666">
				<div class="post-metadata">
					<div class="post-num">Post #1</div>
					<div class="post-author">andrea.buono</div>
					<div class="post-datetime">
						16 Nov 2013, 10:33					</div>
				</div>
				<div class="post-content content">
					<p>Hi to everyone and good morning,<br />first of all sorry for my english,</p><p>so I have installed pyload on a 1043nd with the last snapshot of Barrier Breaker without error but when I run pyload after the configuration pyload can&#039;t reach internet because the &quot;update&quot; script give me a warning that can&#039;t reach the server for the updates and when I add my login data for easybytez I give an error in login.<br />Now I&#039;m sure about my login data because the windows version of pyload work correctly.<br />After run pyload in debug mode no useful information, maybe is there a possibility to make in debug mode also the update plugin but I don&#039;t know how do that.<br />I&#039;m quite sure that is a firewall problem but after many hour to find a solution at the moment not luck, and finally I disturb you with my problem.<br />I hope that someone can help me.</p><p>Best regards.</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p217694">
				<div class="post-metadata">
					<div class="post-num">Post #2</div>
					<div class="post-author">andrea.buono</div>
					<div class="post-datetime">
						16 Nov 2013, 16:06					</div>
				</div>
				<div class="post-content content">
					<p>This is my traceback, seems some problem related to &quot;HTTPRequest.py&quot;</p><br /><p>Traceback (most recent call last):<br />&nbsp; File &quot;/usr/share/python/pyload/module/HookManager.py&quot;, line 88, in new<br />&nbsp; &nbsp; return func(*args)<br />&nbsp; File &quot;/usr/share/python/pyload/module/HookManager.py&quot;, line 198, in coreReady<br />&nbsp; &nbsp; plugin.coreReady()<br />&nbsp; File &quot;/usr/share/python/pyload/module/plugins/hooks/LinkdecrypterCom.py&quot;, line 34, in coreReady<br />&nbsp; &nbsp; page = getURL(&quot;http://linkdecrypter.com/&quot;)<br />&nbsp; File &quot;/usr/share/python/pyload/module/network/RequestFactory.py&quot;, line 122, in getURL<br />&nbsp; &nbsp; return pyreq.getURL(*args, **kwargs)<br />&nbsp; File &quot;/usr/share/python/pyload/module/network/RequestFactory.py&quot;, line 67, in getURL<br />&nbsp; &nbsp; rep = h.load(*args, **kwargs)<br />&nbsp; File &quot;/usr/share/python/pyload/module/network/HTTPRequest.py&quot;, line 188, in load<br />&nbsp; &nbsp; self.setRequestContext(url, get, post, referer, cookies, multipart)<br />&nbsp; File &quot;/usr/share/python/pyload/module/network/HTTPRequest.py&quot;, line 180, in setRequestContext<br />&nbsp; &nbsp; self.c.setopt(pycurl.COOKIEFILE, &quot;&quot;)<br />error: (48, &#039;&#039;)</p><p>does someone have some idea? maybe a curl library problem?</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p217695">
				<div class="post-metadata">
					<div class="post-num">Post #3</div>
					<div class="post-author">andrea.buono</div>
					<div class="post-datetime">
						16 Nov 2013, 16:15					</div>
				</div>
				<div class="post-content content">
					<p>Found that the error 48 is a socket error......</p>									</div>
			</article>

			
		
			
		
		
			<article class="post" id="p219204">
				<div class="post-metadata">
					<div class="post-num">Post #4</div>
					<div class="post-author">ventura8</div>
					<div class="post-datetime">
						4 Dec 2013, 18:19					</div>
				</div>
				<div class="post-content content">
					<p>I have the exact same issue. Any solutions?<br />I am on AC66U, KongMod 23020, with opkg</p>									</div>
			</article>

			
		
	
			<div class="notice minor">
			<p>The discussion might have continued from here.</p>
		</div>
	
	<div class="pagination"><div class="pagination-number">Page 1 of 1</div><nav><ul><li class="pagination-current"><span>1</span></li></ul></nav></div>
</main>

</div>


<!-- Created in a hurry and not indicative of usual code quality. Here's a number: 0 -->

</body>
</html>